### ISSUE TITLE
The choosing menu do not show up

### ISSUE THREAD

**Issue by romankysely** [tkoecker/OctoPrint-Mmu2filamentselect#5] opened 2021-04-07 20:01 UTC
Hi,
when I start print, the menu for choosing fillament do not showup. When I can expect menu? Immediately after push Print button or lately after warmup of nozzle and bed?

Thx a lot for help.
Roman

**Configuration:**
MK3S+MMU2S latest FW configured as Single
PrusaSlicer 2.3.0
OctoPrint 1.5.3
OctoPi 0.18
[System Information OctoPrint.txt](https://github.com/tkoecker/OctoPrint-Mmu2filamentselect/files/6274117/System.Information.OctoPrint.txt)

Prusa MMU2 Select Filament: 1.0.3 
GCode file from PrusaSlicer:
[test_gcode.zip](https://github.com/tkoecker/OctoPrint-Mmu2filamentselect/files/6274096/test_gcode.zip)

**Comment by IzK666** [comment] 2021-04-11 17:05
The choosing menu doesn't appears when the file is printed from the SD.
Can you fix it?

**Comment by romankysely** [comment] 2021-04-14 16:40
Thx for reply. I do not print from SD card. I am printing via Octopi. PrusaSlicer send gcode diretly to Octoprint and there I choose file from menu and push Print button. The file with gcode is stored in Octoprint server. Any idea? thx

**Comment by romankysely** [comment] 2021-04-22 14:35
The problem was at profiles of PrusaSlicer 2.3. They did not generate Tx command in GCode.

**Comment by JKinch03** [comment] 2021-04-23 20:34
Hey @romankysely. You might want to check in the Octoprint settings for your printer configuration. I don't remember the exact menu path, but it should be under settings, and you should see something along the lines of an "about your printer" menu. You'll need to change the number of nozzles on the printer to 5 for the plugin to work properly.
Hope this helps!
-JKinch

**Comment by tkoecker** [comment] 2021-06-06 21:17
Yes, the dialog only shows up if the generated gcode contains "Tx"
Closing issue as the cause was found.

**Closed as completed by tkoecker** 2021-06-06 21:17 UTC
